use_frameworks!

platform :ios, '12.2'

target 'Sandbox' do
  #pod 'IdentitySdkCore', '5.0.0'
  #pod 'IdentitySdkWebView', '5.0.0'
  #pod 'IdentitySdkGoogle', '5.0.0'
  #pod 'IdentitySdkFacebook', '5.0.0'
  
  # Dev mode
  pod 'IdentitySdkCore', :path => '../IdentitySdkCore.podspec'
  pod 'IdentitySdkWebView', :path => '../IdentitySdkWebView.podspec'
  pod 'IdentitySdkGoogle', :path => '../IdentitySdkGoogle.podspec'
  pod 'IdentitySdkFacebook', :path => '../IdentitySdkFacebook.podspec'

  pod 'AlamofireNetworkLogger'
end
