source 'https://cdn.cocoapods.org/'

# Comment the next line to not define a global platform for your project
platform :ios, '13.0'

target 'IdentitySdkCore' do
  # Comment the next line if you do not want to use dynamic frameworks
  use_frameworks!

  # Pods for IdentitySdkCore
  pod 'Alamofire', '~> 5.6.1'
  pod 'BrightFutures', '~> 8.2.0'
  pod 'EllipticCurveKeyPair', '~> 2.0'
  pod 'KeychainAccess', '~> 4.2.1'
  pod 'PromiseKit', '~> 6.18.0'
  pod 'CryptoSwift', '~> 1.5.1'

end
